name: Test Live Share SDK packages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm --loglevel verbose ci --ignore-scripts
              timeout-minutes: 20

            - run: npm run prepare # will trigger a build of all packages

            - name: "test live-share"
              run: npm run test
              working-directory: packages/live-share

            - name: "test live-share-canvas"
              run: npm run test
              working-directory: packages/live-share-canvas

            - name: "test live-share-media"
              run: npm run test
              working-directory: packages/live-share-media