name: Build Live Share SDK samples

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm --loglevel verbose ci --ignore-scripts
              timeout-minutes: 20

            # fix for v1
            #- run: npm install jest
              #working-directory: samples/javascript/02.react-video

            - name: "build packages and samples"
              run: npm run build

            # TODO: get scenario_test.sh working

            # - name: "test 02.react-video sample"
            #   shell: "bash"
            #   run: sh ../../../.github/workflows/scenario_test.sh
            #   working-directory: samples/javascript/02.react-video