name: Build Live Share SDK samples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install jest
        working-directory: samples/javascript/02.react-video

      - name: "build packages and samples"
        run: npm run build

      - name: "test 02.react-video sample"
        shell: "bash"
        run: sh ../../../.github/workflows/scenario_test.sh
        working-directory: samples/javascript/02.react-video
