name: Check formatting

on:
    push:
        branches: [main, mainv2]
    pull_request:
        branches: [main, mainv2]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install

            - name: "check formatting"
              run: "bash checkFormatting.sh"
              working-directory: .github/workflows
