name: Test Live Share SDK packages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm --loglevel verbose ci --ignore-scripts
              timeout-minutes: 20

            - run: npm run build:packages

            - name: "test live-share"
              run: npm run test
              working-directory: packages/live-share

            - name: "test live-share-canvas"
              run: npm run test
              working-directory: packages/live-share-canvas

            - name: "test live-share-media"
              run: npm run test
              working-directory: packages/live-share-media

            - name: "test live-share-turbo"
              run: npm run test
              working-directory: packages/live-share-turbo